### ISSUE TITLE
Example is broken

### ISSUE THREAD

**Issue by rahul0x24** [mattDavo/EditorExample#1]
Hi matt

I was trying to run this example but it failed to compile. I have a use case too where I need some editor features and right now I am using Highlightr. It does the job but this would be so much better. I have gone through some articles to understand the grammar and will try to contribute to this if you are not abandoning it.

**Comment by mattDavo** [comment]
Hey @RahulKatariya!

Thank you for your support. Sorry about the issue you had. The swift package was resolved to an old version of Editor (maybe time to add a release to avoid this in the future). The issue should be fixed now.

I'm super familiar with Swift Package Manager yet, but if you pull and it doesn't automatically update the resolved version of Editor then you can try:
- File > Swift > Packages > Resolve Package Versions (should work)
- File > Swift > Packages > Reset Package Caches (I'm not sure what this does)
- File > Swift > Packages > Update to Latest Package Versions (last resort, will work)

Feel free to reach out if you have trouble understanding how to write your grammars or themes. If there are missing features I don't have the time to contribute right now but would be more than happy to help you.

**Comment by rahul0x24** [comment]
Thanks for the quick reply.  Updating to latest versions did the trick. I had to add the fonts from google as you used custom fonts. 

I saw that vscode used some oniguruma for regex as textmate grammar itself suggests that. Is it something already supported by Swift? I have seen wrappers not mentioning anything like that anywhere. Did you investigate this?

**Comment by mattDavo** [comment]
Oh sorry. I think I have that font installed on my computer by default 😅

Nah I don't use the oniguruma regex engine. Just the Swift standard library one.

**Comment by rahul0x24** [comment]
Ah Alright. I will try to dig into in if I am able to find time from my work 😪. 

What you have built so far is awesome 🤩 Thanks so much for sharing.

**Comment by mattDavo** [comment]
Great! Cheers, I'm looking forward to hearing how you find it!
